from tkinter import *
a = Tk()
a.title("Student Info")
a.geometry("350x350")
n = Label(a, text = "Name")
n.grid(row=0, column=0)
e1 = Entry(a)
e1.grid(row=0, column=1)
r = Label(a, text="Roll No: ")
r.grid(row=1, column=0)
e2 = Entry(a)
e2.grid(row=1, column=1)
b = Button(a, text="Submit")
b.grid(row=2, column=0)
cb1 = Checkbutton(a, text="AIML")
cb1.grid(row=3, column=0)
cb2= Checkbutton(a, text="CSE")
cb2.grid(row=4, column=0)
l1 = Label(a, text="Programming Language known")
l1.grid(row=5, column=1)
lb1 = Listbox(a, height=3)
lb1.insert(1, "Java")
lb1.insert(2, "Python") 
lb1.insert(3, "C++")
lb1.grid(row=6, column=1)
rb1=Radiobutton(a, text="MALE", value=1)
rb1.grid(rows=7, column=0)
rb2=Radiobutton(a, text="FEMALE", value=2)
rb2.grid(rows=8, column=0)
b1=Button(a, text="Submit")
b1.grid(rows=9, column=1)
a.mainloop()
